#!/bin/bash
universe = vanilla
log    =    log/test_$(Process).log
error  =  error/test_$(Process).err
output = output/test_$(Process).out

executable = ./test.sh

arguments = $(Process) 

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = files.txt,http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz, fastICA_1.2-2.tar.gz,ica.R,/home/xmiao27/data_eeg_age_v1/data2kaggle/eval/$(Process)

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue Process from files.txt
